// ---------------------------------------------------------------------------
// Refresh the self-hosted fonts.
//
//   node scripts/fetch-fonts.mjs
//
// Downloads the latin cut of each family from Google and writes them into
// src/css/fonts/, then regenerates src/css/_fonts.scss to point at them. Run it
// only when the set of families or weights changes — the files it writes are
// committed, and the app never talks to Google at runtime. See "Fonts" in
// CLAUDE.md for why they are local.
// ---------------------------------------------------------------------------

import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'src/css/fonts')

// A Chrome UA is what makes the API hand over woff2 rather than the older
// formats it keeps around for ancient browsers.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

// Baloo is asked for as a weight *range*, which returns one variable file
// covering 500–800. Asking for the four weights separately returns four static
// files and about 100 KB more.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Baloo+2:wght@500..800' +
  '&family=Courier+Prime:ital,wght@0,400;0,700;1,400' +
  '&family=Press+Start+2P' +
  '&display=swap'

const res = await fetch(CSS_URL, { headers: { 'user-agent': UA } })
if (!res.ok) throw new Error(`Google Fonts said ${res.status}`)
const css = await res.text()

// Google emits "/* latin */" before each @font-face. The console is an English
// love letter, so the vietnamese and latin-ext cuts are weight nobody here will
// ever render.
const wanted = css
  .split('/*')
  .slice(1)
  .filter((block) => block.trimStart().startsWith('latin */'))

if (!wanted.length) throw new Error('no latin faces found — did the CSS format change?')

await mkdir(OUT_DIR, { recursive: true })

// Clear the old files first, or a renamed weight leaves an orphan behind that
// nothing references and everything ships.
for (const name of await readdir(OUT_DIR)) {
  if (name.endsWith('.woff2')) await unlink(join(OUT_DIR, name))
}

const rules = []
let index = 0

for (const block of wanted) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim()
  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim()
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  if (!family || !url) continue

  const slug =
    `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${weight.replace(/\s+/g, '')}` +
    `${style === 'italic' ? '-italic' : ''}-${index++}.woff2`

  const file = await fetch(url, { headers: { 'user-agent': UA } })
  const bytes = Buffer.from(await file.arrayBuffer())
  await writeFile(join(OUT_DIR, slug), bytes)

  rules.push(
    [
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('./fonts/${slug}') format('woff2');`,
      '}',
    ].join('\n'),
  )
  console.log(`${slug}  ${(bytes.length / 1024).toFixed(1)} KB  <-  ${family} ${weight} ${style}`)
}

const header = `// ---------------------------------------------------------------------------
// The three fonts, served by the app itself rather than by Google.
//
// GENERATED by scripts/fetch-fonts.mjs — run that rather than editing this.
//
// They are local because an installed app has to render as itself with the
// network off, and a stylesheet fetched from another origin during the initial
// parse is requested before the service worker controls the page, so it never
// reaches the cache on a first visit. It also drops a third-party round trip
// from first paint and keeps working on networks where Google Fonts does not.
//
// Baloo 2, Courier Prime and Press Start 2P are all under the SIL Open Font
// License 1.1 — see fonts/OFL.txt. Only the latin cut of each is kept.
// ---------------------------------------------------------------------------

`

await writeFile(join(ROOT, 'src/css/_fonts.scss'), header + rules.join('\n\n') + '\n')
console.log(`\n${rules.length} faces -> src/css/_fonts.scss`)
